name: "@muukii/chglog-action"
description: "Generates a changelog between refs"
inputs:
  left-ref: # id of input
    description: "base ref"
    required: true
  right-ref:
    description: "head ref"
    required: true
outputs:
  text: # output will be available to future steps
    description: "The text generated"
runs:
  using: "node12"
  main: "dist/index.js"
